"""`ug` — ultragraph CLI for the five core workflows.

Usage::

    ug pull <name>              Download and verify a deployed model
    ug new <name>               Scaffold a new project
    ug report <checkpoint>      Generate an HTML report from a trained model
    ug practice [--steps N]     Short training session with progress report
    ug breed <a> <b> --ratio R  Average two deployed checkpoints
    ug compile <model> <target>  Compile to .ugm or other targets
    ug run <file.ugm>            Execute a .ugm module
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path

import numpy as np

_HUB_BASE = os.environ.get("ULTRAGRAPH_HUB", "https://ultragraph.dev/models")


# ---------------------------------------------------------------------------
# pull  — download and verify a deployed model
# ---------------------------------------------------------------------------
def cmd_pull(args: argparse.Namespace) -> None:
    name = args.name
    url = args.url or f"{_HUB_BASE}/{name}.npz"
    dest = Path(args.dir) / f"{name}.npz"
    dest.parent.mkdir(parents=True, exist_ok=True)

    print(f"↓ Pulling {name} from {url}")
    try:
        urllib.request.urlretrieve(url, dest)
    except Exception as e:
        print(f"✗ Download failed: {e}", file=sys.stderr)
        raise SystemExit(1) from e

    # verify the deployed-model contract: must have __meta__
    try:
        data = np.load(dest, allow_pickle=False)
        meta = json.loads(str(data["__meta__"]))
    except Exception as e:
        dest.unlink(missing_ok=True)
        print(f"✗ Invalid checkpoint (no __meta__): {e}", file=sys.stderr)
        raise SystemExit(1) from e

    hp = meta.get("hp", {})
    size = dest.stat().st_size
    print(f"✓ {name}.npz  ({size / 1024:.0f} KB, {hp.get('d_model','?')}dim / {hp.get('n_layers','?')}layers)")
    print(f"  Load with:  GPT.load_deployed('{dest}')")


# ---------------------------------------------------------------------------
# new  — scaffold a project
# ---------------------------------------------------------------------------
_NEW_DIRS = ("corpus", "checkpoints")
_JUSTFILE = """\
# {{ name }} — auto-generated by `ug new`
default:
    @just --list

# Fetch and enrich the corpus
corpus:
    uv run -m ultragraph.cli pull {{ lang }} --dir corpus/

# Train the model (short practice run)
practice:
    uv run -m ultragraph.cli practice --corpus corpus/ --steps 100

# Train the model (full)
train:
    uv run python -c "
from ultragraph import GPT, ByteTokenizer, Adam, CosineSchedule
tok = ByteTokenizer()
model = GPT(vocab=256, d_model=128, n_layers=4, n_heads=4)
# ... training loop reads from corpus/
model.save('checkpoints/model.npz')
"

# Generate a report from a trained checkpoint
report:
    uv run -m ultragraph.cli report checkpoints/model.npz

# Chat with the deployed model
chat:
    uv run python -c "
from ultragraph import GPT, ByteTokenizer
tok = ByteTokenizer()
m = GPT.load_deployed('checkpoints/model.q.npz')
while True:
    ids = tok.encode(input('> '))
    out = m.generate(ids, n_new=64, temperature=0.8)
    print(tok.decode(out))
"
"""
_TRAIN_YML = """\
# {{ name }} — training config
lang: {{ lang }}
d_model: 128
n_layers: 4
n_heads: 4
max_len: 256
steps: 5000
"""  # noqa: E501


def cmd_new(args: argparse.Namespace) -> None:
    name = args.name
    lang = args.lang or "english"
    root = Path.cwd() / name
    if root.exists():
        print(f"✗ {root} already exists", file=sys.stderr)
        raise SystemExit(1)

    root.mkdir(parents=True)
    for d in _NEW_DIRS:
        (root / d).mkdir()
    (root / ".gitignore").write_text("__pycache__/\n*.pyc\n.venv/\n")
    (root / "train.yml").write_text(_TRAIN_YML.replace("{{ name }}", name).replace("{{ lang }}", lang))
    (root / "justfile").write_text(_JUSTFILE.replace("{{ name }}", name).replace("{{ lang }}", lang))

    print(f"✓ Scaffolded {name}/")
    print(f"  cd {name} && just corpus    # fetch corpus")
    print(f"  cd {name} && just practice  # quick training")
    print(f"  cd {name} && just train     # full training")


# ---------------------------------------------------------------------------
# report  — generate an HTML report from a checkpoint
# ---------------------------------------------------------------------------
def cmd_report(args: argparse.Namespace) -> None:
    from .model import GPT

    path = Path(args.checkpoint)
    if not path.exists():
        print(f"✗ {path} not found", file=sys.stderr)
        raise SystemExit(1)

    # Detect deployed vs training checkpoint
    try:
        data = np.load(path, allow_pickle=False)
        if "__meta__" in data.files:
            model = GPT.load_deployed(str(path))
        else:
            raise ValueError("training checkpoint — load via model.load()")
    except Exception:
        # Try as training checkpoint
        print("⚠ Deployed checkpoint not detected; run ug report on .q.npz")
        raise SystemExit(1)

    html = _build_report(model, path)
    report_path = path.with_suffix(".html")
    report_path.write_text(html, encoding="utf-8")
    print(f"✓ Report: {report_path}")


def _build_report(model, path: Path) -> str:
    from .tokenize import ByteTokenizer
    from .viz.svg import byte_heatmap_svg

    tok = ByteTokenizer()
    n_params = model.n_params()
    size = path.stat().st_size

    # Sample generations
    samples = []
    for temp in (0.0, 0.6, 0.9):
        try:
            ids = model.generate([72, 105], n_new=48, temperature=temp, top_k=40)
            text = tok.decode(ids)
        except Exception as e:
            text = f"[error: {e}]"
        samples.append((temp, text))

    # Weight statistics
    rows = []
    for i, t in enumerate(model._dense_trees()):
        wq = np.asarray(t.wq)
        total = wq.size
        sparsity = float((wq == 0).sum()) / total * 100 if total else 0
        pos = float((wq > 0).sum()) / total * 100 if total else 0
        neg = float((wq < 0).sum()) / total * 100 if total else 0
        hm = byte_heatmap_svg(wq)
        rows.append(f"<tr><td>{t.name}</td><td>{'×'.join(str(s) for s in wq.shape)}</td>"
                    f"<td>{sparsity:.0f}%</td><td>{pos:.0f}%</td><td>{neg:.0f}%</td>"
                    f"<td>{hm}</td></tr>")

    # Build HTML
    samples_html = "".join(
        f"<h3>Temperature {t}</h3><pre>{s}</pre>" for t, s in samples
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>ultragraph Report — {path.name}</title>
<style>
  body {{ font-family: sans-serif; max-width: 960px; margin: 2em auto; background: #fafafa; color: #222; }}
  h1 {{ border-bottom: 2px solid #4a6fa5; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #ccc; padding: 6px; text-align: center; font-size: 13px; }}
  th {{ background: #4a6fa5; color: #fff; }}
  pre {{ background: #eee; padding: 1em; overflow-x: auto; }}
  svg {{ max-width: 120px; max-height: 60px; }}
</style></head><body>
<h1>ultragraph Report</h1>
<p><strong>Checkpoint:</strong> {path.name} ({size / 1024:.0f} KB)</p>
<p><strong>Parameters:</strong> {n_params:,}</p>
<h2>Weight Statistics</h2>
<table>
<tr><th>Layer</th><th>Shape</th><th>Sparsity</th><th>Pos %</th><th>Neg %</th><th>Heatmap</th></tr>
{''.join(rows)}
</table>
<h2>Samples</h2>
{samples_html}
</body></html>"""


# ---------------------------------------------------------------------------
# practice  — short training session
# ---------------------------------------------------------------------------
def cmd_practice(args: argparse.Namespace) -> None:
    from .model import GPT
    from .optim import SGD
    from .tokenize import ByteTokenizer

    steps = int(args.steps)
    corpus_dir = Path(args.corpus) if args.corpus else Path.cwd() / "corpus"

    # Find or create a tiny corpus
    texts = []
    if corpus_dir.is_dir():
        for f in sorted(corpus_dir.glob("*.txt")):
            texts.append(f.read_text(encoding="utf-8", errors="replace"))
    if not texts:
        texts = ["hello ultra graph world. this is a tiny practice corpus. " * 20]

    corpus = "\n".join(texts)
    tok = ByteTokenizer()
    ids = tok.encode(corpus)

    # Tiny GPT
    model = GPT(vocab=256, d_model=32, n_layers=2, n_heads=2, max_len=64)
    opt = SGD(model, lr=0.1, momentum=0.9)

    prev_loss = float("inf")
    for step in range(steps):
        chunk = ids[step % (len(ids) - 64): step % (len(ids) - 64) + 64]
        inp = chunk[:-1]
        tgt = chunk[1:]
        logits = model(inp)
        loss = logits.cross_entropy(tgt)
        opt.zero_grad()
        loss.backward()
        opt.step()
        loss_val = float(loss.data)

        if step % 10 == 0 or step == steps - 1:
            delta = f" ({'↓' if loss_val < prev_loss else '↑'})" if step > 0 else ""
            print(f"  step {step:>4}  loss {loss_val:.4f}{delta}")
            prev_loss = loss_val

    sample = tok.decode(model.generate([72, 105], n_new=32, temperature=0.8))
    print(f"\n✓ {steps} steps complete")
    print(f"  Final loss: {loss_val:.4f}")
    print(f"  Sample: {sample[:80]}...")


# ---------------------------------------------------------------------------
# breed  — average two deployed checkpoints
# ---------------------------------------------------------------------------
def cmd_breed(args: argparse.Namespace) -> None:
    import json as _json

    a_path = Path(args.model_a)
    b_path = Path(args.model_b)
    if not a_path.exists():
        print(f"✗ {a_path} not found", file=sys.stderr)
        raise SystemExit(1)
    if not b_path.exists():
        print(f"✗ {b_path} not found", file=sys.stderr)
        raise SystemExit(1)

    ratio = float(args.ratio) if args.ratio is not None else 0.5
    if not (0.0 <= ratio <= 1.0):
        print(f"✗ ratio must be in [0, 1], got {ratio}", file=sys.stderr)
        raise SystemExit(1)

    a_data = np.load(a_path, allow_pickle=False)
    b_data = np.load(b_path, allow_pickle=False)

    # Use A's meta as base, merge hp names
    a_meta = _json.loads(str(a_data["__meta__"]))
    merged_hp = dict(a_meta.get("hp", {}))
    merged_hp["parents"] = [a_path.name, b_path.name]
    merged_hp["breed_ratio"] = ratio

    arrays = {}
    for key in a_data.files:
        if key == "__meta__":
            continue
        if key not in b_data.files:
            print(f"  ⚠ key {key} only in parent A, using as-is")
            arrays[key] = a_data[key]
            continue
        a_arr = a_data[key].copy()
        b_arr = b_data[key]
        if a_arr.shape != b_arr.shape:
            print(f"  ⚠ shape mismatch for {key}: {a_arr.shape} vs {b_arr.shape}, using A")
            arrays[key] = a_arr
        else:
            arrays[key] = (a_arr * (1 - ratio) + b_arr * ratio).astype(a_arr.dtype)

    # Default output name
    a_stem = a_path.stem.replace(".q", "")
    b_stem = b_path.stem.replace(".q", "")
    out_name = args.output or f"{a_stem}-x-{b_stem}.npz"
    out_path = Path(out_name)
    arrays["__meta__"] = np.array(_json.dumps({**a_meta, "hp": merged_hp}))
    np.savez(out_path, **arrays)

    size = out_path.stat().st_size
    print(f"✓ Bred {a_path.name} × {b_path.name} (ratio={ratio}) → {out_path} ({size / 1024:.0f} KB)")


# ---------------------------------------------------------------------------
# compile  — compile a model to .ugm or other target
# ---------------------------------------------------------------------------
def cmd_compile(args: argparse.Namespace) -> None:
    from .model import GPT
    from .ugm import from_ultragraph, save_ugm

    model_path = Path(args.model)
    target = args.target
    data = np.load(model_path, allow_pickle=False)

    if "__meta__" in data.files:
        model = GPT.load_deployed(str(model_path))
    else:
        print("⚠ Training checkpoint detected; need deployed .npz", file=sys.stderr)
        raise SystemExit(1)

    if target == "ugm" or target.endswith(".ugm"):
        out = Path(target) if target.endswith(".ugm") else model_path.with_suffix(".ugm")
        module = from_ultragraph(model)
        save_ugm(out, module)
        print(f"✓ Compiled {model_path.name} → {out} ({out.stat().st_size / 1024:.0f} KB)")
    else:
        print(f"✗ Unknown target: {target} (supported: ugm)", file=sys.stderr)
        raise SystemExit(1)


# ---------------------------------------------------------------------------
# run  — execute a .ugm module
# ---------------------------------------------------------------------------
def cmd_run(args: argparse.Namespace) -> None:
    from .ugm import load_ugm

    path = Path(args.file)
    if not path.exists():
        print(f"✗ {path} not found", file=sys.stderr)
        raise SystemExit(1)

    module = load_ugm(str(path))
    if args.info:
        print(f"{path.name}: {len(module.trees)} trees, {len(module.ultra_edges)} ultra-edges")
        for i, t in enumerate(module.trees):
            print(f"  tree[{i}]: {t.name} ({'dense' if t.kind == 0 else 'sparse'}, "
                  f"{t.in_dim}→{t.out_dim}, act={t.act})")
        return

    in_dim = module.trees[0].in_dim if module.trees else 1
    x = np.random.randn(1, in_dim).astype(np.float32)
    out = module.run(x)
    print(f"✓ {path.name} forward: [{out.shape[1]}] output (sum={float(out.sum()):.2f})")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="ug", description="ultragraph CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    p_pull = sub.add_parser("pull", help="Download and verify a deployed model")
    p_pull.add_argument("name", help="Model name (e.g. hungarian)")
    p_pull.add_argument("--url", help="Override download URL")
    p_pull.add_argument("--dir", default="examples/data", help="Output directory")

    p_new = sub.add_parser("new", help="Scaffold a new project")
    p_new.add_argument("name", help="Project name")
    p_new.add_argument("--lang", default="english", help="Target language")

    p_report = sub.add_parser("report", help="Generate HTML report from checkpoint")
    p_report.add_argument("checkpoint", help="Path to .npz checkpoint")

    p_practice = sub.add_parser("practice", help="Short training session")
    p_practice.add_argument("--steps", default=100, help="Number of training steps")
    p_practice.add_argument("--corpus", help="Path to corpus directory")

    p_breed = sub.add_parser("breed", help="Average two deployed checkpoints")
    p_breed.add_argument("model_a", help="First deployed checkpoint")
    p_breed.add_argument("model_b", help="Second deployed checkpoint")
    p_breed.add_argument("--ratio", type=float, default=0.5, help="Blend ratio (0 = pure A, 1 = pure B)")
    p_breed.add_argument("--output", "-o", help="Output path")

    p_compile = sub.add_parser("compile", help="Compile model to .ugm")
    p_compile.add_argument("model", help="Deployed .npz checkpoint")
    p_compile.add_argument("target", nargs="?", default="ugm", help="Target format (ugm)")

    p_run = sub.add_parser("run", help="Execute a .ugm module")
    p_run.add_argument("file", help="Path to .ugm file")
    p_run.add_argument("--info", action="store_true", help="Print module info only")

    args = parser.parse_args(argv)
    if args.command == "pull":
        cmd_pull(args)
    elif args.command == "new":
        cmd_new(args)
    elif args.command == "report":
        cmd_report(args)
    elif args.command == "practice":
        cmd_practice(args)
    elif args.command == "breed":
        cmd_breed(args)
    elif args.command == "compile":
        cmd_compile(args)
    elif args.command == "run":
        cmd_run(args)


if __name__ == "__main__":
    main()
