"""RP2040 target — bare-metal C code generator for embedded inference.

Generates a single C source file with:
- Tree weights as const int8 arrays in flash
- Bias arrays as const float32
- Forward pass as C function
- Main function that reads input and prints output

No OS, no heap, no dynamic allocation. Runs on RP2040 (256 KB RAM, 2 MB flash).

Usage::

    ug compile model.ugm --target rp2040
"""


from pathlib import Path

import numpy as np

from .ugm import (
    ACT_NONE,
    ACT_RELU,
    ACT_SIGMOID,
    ACT_TANH,
    KIND_DENSE,
    UE_RESIDUAL,
    UGMFile,
)

_ACT_C = {
    ACT_NONE: "/* none */",
    ACT_RELU: "if (out[o] < 0.0f) out[o] = 0.0f;",
    ACT_SIGMOID: "out[o] = 1.0f / (1.0f + expf(-out[o]));",
    ACT_TANH: "out[o] = tanhf(out[o]);",
}


def _c_array_int8(name: str, arr: np.ndarray) -> str:
    flat = arr.flatten()
    elems = ", ".join(str(int(x)) for x in flat)
    return f"static const int8_t {name}[{flat.size}] = {{{elems}}};"


def _c_array_f32(name: str, arr: np.ndarray) -> str:
    flat = arr.flatten()
    elems = ", ".join(f"{float(x):.6g}f" for x in flat)
    return f"static const float {name}[{flat.size}] = {{{elems}}};"


def _resolve_order(module: UGMFile) -> list[int]:
    incoming: dict[int, list] = {i: [] for i in range(len(module.trees))}
    for ue in module.ultra_edges:
        incoming[ue.dst_idx].append(ue)
    remaining = set(range(len(module.trees)))
    order: list[int] = []
    while remaining:
        progressed = False
        for ti in list(remaining):
            if all(e.src_idx in set(order) for e in incoming[ti]):
                order.append(ti)
                remaining.remove(ti)
                progressed = True
        if not progressed:
            msg = "cycle detected"
            raise ValueError(msg)
    return order


def _check_supported(module: UGMFile, order: list[int]) -> None:
    """Fail loudly on graphs the RP2040 backend cannot compile correctly.

    ``generate_c`` runs trees as a straight-line ping-pong pipeline, which only
    models a *plain linear chain*: one source tree, and every subsequent tree
    fed by exactly one plain ultra-edge from its predecessor. Residual edges
    and branch/merge topologies are not modelled — rather than silently emit
    wrong C, we raise here. Use the WASM backend (``ultragraph.wasm``), whose
    per-tree scratch buffers do support residual/merge graphs.
    """
    if any(ue.kind == UE_RESIDUAL for ue in module.ultra_edges):
        msg = (
            "RP2040 backend supports plain linear chains only; residual "
            "ultra-edges are not implemented. Use the WASM backend "
            "(ultragraph.wasm) for residual graphs."
        )
        raise NotImplementedError(msg)
    incoming: dict[int, list] = {i: [] for i in range(len(module.trees))}
    for ue in module.ultra_edges:
        incoming[ue.dst_idx].append(ue)
    for pos, ti in enumerate(order):
        edges = incoming[ti]
        expected = 0 if pos == 0 else 1
        if len(edges) != expected or (pos > 0 and edges[0].src_idx != order[pos - 1]):
            msg = (
                "RP2040 backend supports plain linear chains only; a "
                f"branch/merge was detected (tree {ti} has {len(edges)} "
                "incoming edge(s)). Use the WASM backend (ultragraph.wasm) "
                "for branch/merge graphs."
            )
            raise NotImplementedError(msg)


def generate_c(module: UGMFile, name: str = "model") -> str:
    """Generate C source code for bare-metal inference."""
    order = _resolve_order(module)
    _check_supported(module, order)
    lines: list[str] = []

    lines.append(f"/* {name}.c — generated by ug compile --target rp2040 */")
    lines.append("/* Bare-metal C, no OS, no heap. RP2040 ready. */")
    lines.append("#include <stdint.h>")
    lines.append("#include <math.h>")
    lines.append("")

    # Emit weight arrays
    for i, tree in enumerate(module.trees):
        if tree.kind == KIND_DENSE and tree.wq is not None:
            lines.append(_c_array_int8(f"t{i}_wq", tree.wq))
            if tree.bias is not None:
                lines.append(_c_array_f32(f"t{i}_bias", tree.bias))
            lines.append(f"static const float t{i}_scale = {tree.w_scale:.6g}f;")
            lines.append("")

    # Forward function for each tree
    for i, tree in enumerate(module.trees):
        if tree.kind != KIND_DENSE:
            continue
        act_code = _ACT_C.get(tree.act, "/* unknown act */")
        lines.append(f"static void tree{i}_forward(const float* inp, float* out) {{")
        lines.append(f"  const int in_dim = {tree.in_dim};")
        lines.append(f"  const int out_dim = {tree.out_dim};")
        lines.append("  for (int o = 0; o < out_dim; o++) {")
        lines.append(f"    float acc = t{i}_bias[o];")
        lines.append("    for (int j = 0; j < in_dim; j++) {")
        lines.append(f"      acc += (float)t{i}_wq[o * in_dim + j] * inp[j] * t{i}_scale;")
        lines.append("    }")
        lines.append("    out[o] = acc;")
        lines.append(f"    {act_code}")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    # Main forward pass — straight-line ping-pong pipeline.
    #
    # The first tree reads the caller's `input`; every later tree reads the
    # buffer the previous tree wrote and writes to the *other* buffer. Source
    # and destination must never be the same array: the per-tree kernel stores
    # out[o] while it is still reading inp[j] over the same index range, so an
    # in-place call (tree(buf, buf)) would corrupt its own inputs mid-pass.
    in_dim = module.trees[order[0]].in_dim if module.trees else 1
    out_dim = module.trees[order[-1]].out_dim if module.trees else 1
    # Buffers must hold the widest activation produced by *any* tree — an
    # intermediate tree can be wider than both the first input and last output.
    buf_size = max(in_dim, max((t.out_dim for t in module.trees), default=1))
    lines.append(f"void {name}_forward(const float* input, float* output) {{")
    if order:
        lines.append(f"  static float buf_a[{buf_size}];")
    if len(order) > 1:
        lines.append(f"  static float buf_b[{buf_size}];")

    prev = "input"
    last = "input"
    for pos, ti in enumerate(order):
        dst = "buf_a" if pos % 2 == 0 else "buf_b"
        lines.append(f"  tree{ti}_forward({prev}, {dst});")
        prev = dst
        last = dst
    lines.append(f"  for (int i = 0; i < {out_dim}; i++) output[i] = {last}[i];")
    lines.append("}")
    lines.append("")

    # Main entry point
    lines.append("#ifdef RP2040")
    lines.append("#include \"pico/stdlib.h\"")
    lines.append("int main() {")
    lines.append("  stdio_init_all();")
    lines.append(f"  float input[{in_dim}] = {{0}};")
    lines.append(f"  float output[{out_dim}];")
    lines.append(f"  {name}_forward(input, output);")
    lines.append(f"  for (int i = 0; i < {out_dim}; i++)")
    lines.append("    printf(\"%f\\n\", output[i]);")
    lines.append("  return 0;")
    lines.append("}")
    lines.append("#endif")
    lines.append("")

    return "\n".join(lines)


def save_rp2040(module: UGMFile, path: str | Path, name: str = "model") -> None:
    """Generate C source and write to file."""
    path = Path(path)
    if path.is_dir():
        path = path / f"{name}.c"
    if not path.suffix:
        path = path.with_suffix(".c")
    c_source = generate_c(module, name=name)
    path.write_text(c_source, encoding="utf-8")
    size = path.stat().st_size
    n_trees = len(module.trees)
    n_weights = sum(t.out_dim * t.in_dim for t in module.trees if t.kind == KIND_DENSE and t.wq is not None)
    print(f"✓ Compiled → {path.name} ({size / 1024:.0f} KB, {n_trees} trees, {n_weights} weights)")
    print(f"  Build: gcc {path.name} -lm -o model && ./model")
    print("  RP2040: pico-sdk + this file = firmware")