"""A mini MCP server (SSE transport) for the ``ultragraph`` 1-bit ternary LLM.

Exposes the deployed Anonymus GPT and the byte tokenizer as MCP tools. Run with::

    uv run --extra mcp python mcp_server/server.py

The SSE endpoint defaults to http://127.0.0.1:8000/sse.
"""
from __future__ import annotations

from pathlib import Path

from mcp.server.fastmcp import FastMCP

from ultragraph import GPT, ByteTokenizer, __version__

mcp = FastMCP("ultragraph")

# <repo>/examples/data/anonymus.gpt.npz — resolved relative to this file (mcp/).
CKPT = Path(__file__).resolve().parent.parent / "examples" / "data" / "anonymus.gpt.npz"

_MODEL: GPT | None = None  # module-level cache: the checkpoint loads once.


def _load_model() -> GPT:
    """Load and cache the deployed Anonymus checkpoint (loaded at most once)."""
    global _MODEL
    if _MODEL is None:
        if not CKPT.exists():
            raise FileNotFoundError(
                f"Deployed checkpoint not found at {CKPT}. "
                "Train it first with: python examples/anonymus_lm.py"
            )
        _MODEL = GPT.load_deployed(str(CKPT))
    return _MODEL


@mcp.tool()
def anonymus_generate(
    prompt: str,
    n_new: int = 120,
    temperature: float = 0.8,
    top_p: float = 0.9,
    seed: int = 0,
) -> str:
    """Generate text with the deployed 1-bit ternary GPT trained on Anonymus'
    *Gesta Hungarorum*.

    Args:
        prompt: Seed text (Latin works best, e.g. "P. dictus magister ").
        n_new: Number of new tokens (bytes) to generate.
        temperature: Sampling temperature; <= 0 is greedy.
        top_p: Nucleus (top-p) sampling threshold.
        seed: RNG seed for reproducible sampling.

    Returns:
        The decoded string (prompt + generated bytes).
    """
    tok = ByteTokenizer()
    model = _load_model()
    ids = tok.encode(prompt)
    out = model.generate(ids, n_new=n_new, temperature=temperature, top_p=top_p, seed=seed)
    return tok.decode(out)


@mcp.tool()
def ultragraph_info() -> dict:
    """Report the installed ultragraph version and deployed-checkpoint status.

    Returns:
        A dict with ``version``, ``deployed_checkpoint_exists`` (bool), and
        ``n_params`` (int, or None if the checkpoint is absent).
    """
    exists = CKPT.exists()
    n_params = _load_model().n_params() if exists else None
    return {
        "version": __version__,
        "deployed_checkpoint_exists": exists,
        "n_params": n_params,
    }


@mcp.tool()
def tokenize_preview(text: str) -> dict:
    """Preview how the byte tokenizer encodes ``text``.

    Args:
        text: Any UTF-8 string.

    Returns:
        A dict with ``n_bytes`` (total byte count) and ``ids_head`` (the first
        32 byte ids).
    """
    ids = ByteTokenizer().encode(text)
    return {"n_bytes": int(ids.size), "ids_head": [int(i) for i in ids[:32]]}


if __name__ == "__main__":
    mcp.run(transport="sse")
